-- MySQL Script generated by MySQL Workbench
-- Fri Sep 27 10:53:46 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema login_nelson
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema login_nelson
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `login_nelson` DEFAULT CHARACTER SET utf8 ;
USE `login_nelson` ;

-- -----------------------------------------------------
-- Table `login_nelson`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login_nelson`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `created_at` TIMESTAMP(2) NULL,
  `deleted_at` TIMESTAMP(2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `login_nelson`.`password`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login_nelson`.`password` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(254) NOT NULL,
  `cliente_id` INT NOT NULL,
  `isValid` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`, `cliente_id`),
  INDEX `fk_password_cliente_idx` (`cliente_id` ASC) ,
  CONSTRAINT `fk_password_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `login_nelson`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `login_nelson`.`rec_password`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login_nelson`.`rec_password` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hash` VARCHAR(254) NULL,
  `created_at` TIMESTAMP(2) NOT NULL,
  `used` TINYINT(1) NOT NULL DEFAULT 0,
  `cliente_id` INT NOT NULL,
  PRIMARY KEY (`id`, `cliente_id`),
  INDEX `fk_rec_password_cliente1_idx` (`cliente_id` ASC) ,
  CONSTRAINT `fk_rec_password_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `login_nelson`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
